<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>cabal</string>
	</array>
	<key>name</key>
	<string>Haskell Cabal syntax</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>--.*</string>
			<key>name</key>
			<string>comment.line.cabal</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s*(?i:\bexecutable\b)</string>
			<key>name</key>
			<string>support.type.cabal</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s*(?i:\blibrary\b)</string>
			<key>name</key>
			<string>support.type.cabal</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s*(?i:\bbenchmark\b)</string>
			<key>name</key>
			<string>support.type.cabal</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s*(?i:\btest-suite\b)</string>
			<key>name</key>
			<string>support.type.cabal</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s*(?i:\bflag\b)</string>
			<key>name</key>
			<string>support.type.cabal</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s*(?i:\bsource-repository\b)</string>
			<key>name</key>
			<string>support.type.cabal</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s*(?i:\btrue\&gt;)</string>
			<key>name</key>
			<string>bool.cabal</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s*(?i:\bfalse\&gt;)</string>
			<key>name</key>
			<string>bool.cabal</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s*(?i:\bauthor\s*(?=:))</string>
			<key>name</key>
			<string>keyword.cabal</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s*(?i:\bbranch\s*(?=:))</string>
			<key>name</key>
			<string>keyword.cabal</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s*(?i:\bbug-reports\s*(?=:))</string>
			<key>name</key>
			<string>keyword.cabal</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s*(?i:\bbuild-depends\s*(?=:))</string>
			<key>name</key>
			<string>keyword.cabal</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s*(?i:\bdefault-language\s*(?=:))</string>
			<key>name</key>
			<string>keyword.cabal</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s*(?i:\bdefault-extensions\s*(?=:))</string>
			<key>name</key>
			<string>keyword.cabal</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s*(?i:\bbuild-tools\s*(?=:))</string>
			<key>name</key>
			<string>keyword.cabal</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s*(?i:\bbuild-type\s*(?=:))</string>
			<key>name</key>
			<string>keyword.cabal</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s*(?i:\bbuildable\s*(?=:))</string>
			<key>name</key>
			<string>keyword.cabal</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s*(?i:\bc-sources\s*(?=:))</string>
			<key>name</key>
			<string>keyword.cabal</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s*(?i:\bcabal-version\s*(?=:))</string>
			<key>name</key>
			<string>keyword.cabal</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s*(?i:\bcategory\s*(?=:))</string>
			<key>name</key>
			<string>keyword.cabal</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s*(?i:\bcc-options\s*(?=:))</string>
			<key>name</key>
			<string>keyword.cabal</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s*(?i:\bcopyright\s*(?=:))</string>
			<key>name</key>
			<string>keyword.cabal</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s*(?i:\bcpp-options\s*(?=:))</string>
			<key>name</key>
			<string>keyword.cabal</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s*(?i:\bdata-dir\s*(?=:))</string>
			<key>name</key>
			<string>keyword.cabal</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s*(?i:\bdata-files\s*(?=:))</string>
			<key>name</key>
			<string>keyword.cabal</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s*(?i:\bdefault\s*(?=:))</string>
			<key>name</key>
			<string>keyword.cabal</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s*(?i:\bdescription\s*(?=:))</string>
			<key>name</key>
			<string>keyword.cabal</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s*(?i:\bexecutable\s*(?=:))</string>
			<key>name</key>
			<string>keyword.cabal</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s*(?i:\bexposed\s*(?=:))</string>
			<key>name</key>
			<string>keyword.cabal</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s*(?i:\bexposed-modules\s*(?=:))</string>
			<key>name</key>
			<string>keyword.cabal</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s*(?i:\bextensions\s*(?=:))</string>
			<key>name</key>
			<string>keyword.cabal</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s*(?i:\bextra-lib-dirs\s*(?=:))</string>
			<key>name</key>
			<string>keyword.cabal</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s*(?i:\bextra-libraries\s*(?=:))</string>
			<key>name</key>
			<string>keyword.cabal</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s*(?i:\bextra-source-files\s*(?=:))</string>
			<key>name</key>
			<string>keyword.cabal</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s*(?i:\bextra-tmp-files\s*(?=:))</string>
			<key>name</key>
			<string>keyword.cabal</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s*(?i:\bfor example\s*(?=:))</string>
			<key>name</key>
			<string>keyword.cabal</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s*(?i:\bframeworks\s*(?=:))</string>
			<key>name</key>
			<string>keyword.cabal</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s*(?i:\bghc-options\s*(?=:))</string>
			<key>name</key>
			<string>keyword.cabal</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s*(?i:\bghc-prof-options\s*(?=:))</string>
			<key>name</key>
			<string>keyword.cabal</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s*(?i:\bghc-shared-options\s*(?=:))</string>
			<key>name</key>
			<string>keyword.cabal</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s*(?i:\bhomepage\s*(?=:))</string>
			<key>name</key>
			<string>keyword.cabal</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s*(?i:\bhs-source-dirs\s*(?=:))</string>
			<key>name</key>
			<string>keyword.cabal</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s*(?i:\bhugs-options\s*(?=:))</string>
			<key>name</key>
			<string>keyword.cabal</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s*(?i:\binclude-dirs\s*(?=:))</string>
			<key>name</key>
			<string>keyword.cabal</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s*(?i:\bincludes\s*(?=:))</string>
			<key>name</key>
			<string>keyword.cabal</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s*(?i:\binstall-includes\s*(?=:))</string>
			<key>name</key>
			<string>keyword.cabal</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s*(?i:\bld-options\s*(?=:))</string>
			<key>name</key>
			<string>keyword.cabal</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s*(?i:\blicense\s*(?=:))</string>
			<key>name</key>
			<string>keyword.cabal</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s*(?i:\blicense-file\s*(?=:))</string>
			<key>name</key>
			<string>keyword.cabal</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s*(?i:\blocation\s*(?=:))</string>
			<key>name</key>
			<string>keyword.cabal</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s*(?i:\bmain-is\s*(?=:))</string>
			<key>name</key>
			<string>keyword.cabal</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s*(?i:\bmaintainer\s*(?=:))</string>
			<key>name</key>
			<string>keyword.cabal</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s*(?i:\bmodule\s*(?=:))</string>
			<key>name</key>
			<string>keyword.cabal</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s*(?i:\bname\s*(?=:))</string>
			<key>name</key>
			<string>keyword.cabal</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s*(?i:\bnhc98-options\s*(?=:))</string>
			<key>name</key>
			<string>keyword.cabal</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s*(?i:\bother-modules\s*(?=:))</string>
			<key>name</key>
			<string>keyword.cabal</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s*(?i:\bpackage-url\s*(?=:))</string>
			<key>name</key>
			<string>keyword.cabal</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s*(?i:\bpkgconfig-depends\s*(?=:))</string>
			<key>name</key>
			<string>keyword.cabal</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s*(?i:\bstability\s*(?=:))</string>
			<key>name</key>
			<string>keyword.cabal</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s*(?i:\bsubdir\s*(?=:))</string>
			<key>name</key>
			<string>keyword.cabal</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s*(?i:\bsynopsis\s*(?=:))</string>
			<key>name</key>
			<string>keyword.cabal</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s*(?i:\btag\s*(?=:))</string>
			<key>name</key>
			<string>keyword.cabal</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s*(?i:\btested-with\s*(?=:))</string>
			<key>name</key>
			<string>keyword.cabal</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s*(?i:\btype\s*(?=:))</string>
			<key>name</key>
			<string>keyword.cabal</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\s*(?i:\bversion\s*(?=:))</string>
			<key>name</key>
			<string>keyword.cabal</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(&gt;=)|(==)|&lt;|(&amp;&amp;)|(&lt;=)</string>
			<key>name</key>
			<string>keyword.operator.cabal</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b\d+(\.\d+(\.\d+(\.\d+)?)?)?\b</string>
			<key>name</key>
			<string>constant.numeric.cabal</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.cabal</string>
	<key>uuid</key>
	<string>02ad6c9b-94ca-4ca2-b2e6-5d6ba6e660bd</string>
</dict>
</plist>
